# Generated by Django 4.1.7 on 2023-03-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commentator',
        ),
    ]
