# Generated by Django 4.1.7 on 2023-03-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_tags_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
