# Generated by Django 4.1.7 on 2023-03-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_articlereading_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topic',
            new_name='title',
        ),
    ]
